# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-21 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 10, 21, 16, 50, 28, 541855, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
